Repository courselab/snaskii21, pull requests merged in 2021-11, with the labels that each got.

#71 Initialized the snake and made a move function
  AUTHORS.md
  src/ttsnake.c
Labels: feature

#79 added arch linux build dependencies on README.md
  README.md
Labels: doc

#89 Improvements in gameplay
  src/ttsnake.c
Labels: feature

#92 Implements spawn of Energy_Blocks
  src/ttsnake.c
Labels: +ciritical, feature

#96 Feature#93
  src/ttsnake.c
Labels: feature

#99 Feature/#95
  src/ttsnake.c
Labels: +ciritical, feature

#98 Improvements to the README.md file
  README.md
Labels: doc, easy

#102 Feature/#101 - Allows the usage of vim keys (hjkl) to move the snake around
  src/ttsnake.c
Labels: feature

#106 Keyboad arrow support
  README.md
  src/ttsnake.c
Labels: feature

#75 Feature/#66
  README.md
  docs/CONTRIBUTING.md
Labels: doc, easy

#114 added 'k' key execution
  src/ttsnake.c
Labels: bug, easy

#107 New template for issues
  .github/ISSUE_TEMPLATE/config.yaml
  .github/ISSUE_TEMPLATE/issue-bug.md
  .github/ISSUE_TEMPLATE/issue-critical.md
  .github/ISSUE_TEMPLATE/issue-doc.md
  .github/ISSUE_TEMPLATE/issue-feature.md
  .github/ISSUE_TEMPLATE/issue-help.md
  .github/ISSUE_TEMPLATE/issue-wontfix.md
Labels: feature

#117 Adding/fixing score shown in screens (closes #111)
  scenes/game/scene-0000002.txt
  src/ttsnake.c
Labels: bug
