Repository courselab/snaskii21, pull requests merged in 2022-01, with the labels that each got.

#207 Add Wall Blocks Feature/#189
  README.md
  src/ttsnake.c
Labels: feature

#296 Fixed block's starting positions parity
  src/ttsnake.c
Labels: +ciritical

#302 Reset scoreboard
  src/ttsnake.c
Labels: feature

#312 Update is even methods
  src/ttsnake.c
Labels: feature

#283 added more boilerplate on pull request template
  docs/CONTRIBUTING.md
  docs/PULL_REQUEST_TEMPLATE.md
  docs/pull_request_template.md
Labels: feature

#290 Remove initial $ on terminal commands
  README.md
  docs/CONTRIBUTING.md
Labels: doc

#294 Add security policy.
  docs/SECURITY.md
Labels: feature
